version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432

  server:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000

volumes:
  postgres_data:

